apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 323149985350.dkr.ecr.us-east-1.amazonaws.com/backend:1.0.0
        ports:
          - containerPort: 3500
        env:
          - name: MYSQL_HOST
            value: mysql

          - name: MYSQL_USER
            value: root

          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_DATABASE

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
